In [1]:
import tensorflow as tf

In [2]:
import numpy as np

### 1. Shape, Rank, Axis

In [9]:
t = tf.constant([[[[1,2,3,4],[5,6,7,8],[9,10,11,12]],
                  [[13,14,15,16],[17,18,19,20],[21,22,23,24]]]])

In [16]:
sess = tf.Session()
sess.run(tf.shape(t))

array([1, 2, 3, 4], dtype=int32)

### 2. Reduce_mean

In [17]:
sess.run(tf.reduce_mean([1,2], axis=0))

1

#### 중요) Axis는 연산하는 차원의 기준을 뜻한다.

In [24]:
x = [[1.,2.],
     [3.,4.],
     [5.,6.]]

Axis = -1은 마지막 차원을 기준으로 연산하는 것을 뜻한다

In [25]:
print(sess.run(tf.reduce_mean(x)))
print(sess.run(tf.reduce_mean(x, axis=0)))
print(sess.run(tf.reduce_mean(x, axis=1)))
print(sess.run(tf.reduce_mean(x, axis=-1)))

3.5
[ 3.  4.]
[ 1.5  3.5  5.5]
[ 1.5  3.5  5.5]


### 3. Argmax

In [34]:
x = [[0,1,2,3],
     [1,2,0,2],
     [1,0,4,1]]
print(sess.run(tf.argmax(x)))
print(sess.run(tf.argmax(x, axis=0)))
print(sess.run(tf.argmax(x, axis=1)))
print(sess.run(tf.argmax(x, axis=-1)))

[1 1 2 0]
[1 1 2 0]
[3 1 2]
[3 1 2]


### 4. Reduce sum

In [35]:
x = [[1.,2.],
     [3.,4.]]

In [39]:
print(sess.run(tf.reduce_sum(x)))
print(sess.run(tf.reduce_sum(x, axis=0)))
print(sess.run(tf.reduce_sum(x, axis=1)))
print(sess.run(tf.reduce_sum(x, axis=-1)))

10.0
[ 4.  6.]
[ 3.  7.]
[ 3.  7.]


In [42]:
print(sess.run(tf.reduce_mean(tf.reduce_sum(x, axis=-1))))

5.0


### 5. reshape

shape의 각 차원의 크기는 해당 차원의 vector 길이를 뜻한다.

In [43]:
t = np.array([[[0,1,2],
               [3,4,5]],
            
              [[6,7,8],
              [9,10,11]]])

In [46]:
t.shape

(2, 2, 3)

In [58]:
np.reshape(t, [-1,1,3]).shape

(4, 1, 3)

In [51]:
sess.run(tf.reshape(t, shape=[-1,3]))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [54]:
sess.run(tf.reshape(t, shape=[-1,1,3]))

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

### 5-1. reshape(squeeze, expand)

In [64]:
sess.run(tf.squeeze([[0],[1],[2]]))

array([0, 1, 2], dtype=int32)

In [67]:
sess.run(tf.expand_dims([0,1,2],1))

array([[0],
       [1],
       [2]], dtype=int32)

### 6. one-hot encoding

In [73]:
t = sess.run(tf.one_hot([[0],[1],[2],[3]], depth=4))
sess.run(tf.one_hot([[0],[1],[2],[3]], depth=4))

array([[[ 1.,  0.,  0.,  0.]],

       [[ 0.,  1.,  0.,  0.]],

       [[ 0.,  0.,  1.,  0.]],

       [[ 0.,  0.,  0.,  1.]]], dtype=float32)

In [71]:
sess.run(tf.reshape(t,shape=[-1,4]))

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]], dtype=float32)

### 7. casting

In [78]:
sess.run(tf.cast([1.8,2.2,3.3,4.9], tf.int32))

array([1, 2, 3, 4], dtype=int32)

### 8. stack

In [81]:
x = [1,4]
y = [2,5]
z = [3,6]

# 행 방향으로 쌓기
sess.run(tf.stack([x,y,z]))

array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)

In [82]:
# 열 방향으로 쌓기
sess.run(tf.stack([x,y,z],axis=-1))

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

### 9. ones and zeros like

In [84]:
x = [[0,1,2],
     [2,1,0]]

sess.run(tf.ones_like(x))

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [85]:
sess.run(tf.zeros_like(x))

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

### 10. zip 함수

In [86]:
for x, y in zip([1,2,3],[4,5,6]):
    print(x, y)

1 4
2 5
3 6


In [87]:
for x,y,z in zip([1,2,3],[4,5,6],[7,8,9]):
    print(x,y,z)

1 4 7
2 5 8
3 6 9
