# Softmax Regression

<img src="./photo/softmax1.png">

### 0. 개념 다지기

1. softmax는 logistic regression의 multiclass 판<br/>
    -> binary classification에서 multiclass classification으로 변경<br/><br/>
    
2. logistic regression의 경우 g(z): sigmoid function으로 H(X)를 0 <= H(X) = g(z) = g(X*w) <=1로 유지하고, 출력을 확률 값으로 변경<br/>
    -> sigmoid regression의 경우 H(X): softmax function(e^Wk.T*x / sigma(e^Wi.T.x))를 사용<br/>
    -> 마찬가지로 각 Class 에 속할 확률으로 표현<br/><br/>

3. costfunction
    -> cross entropy 개념<br/>
    -> D(S, L) = sigma(실제 값(Li) * log(예측값=softmax(i))<br/>
    -> W = W - learning_rate * derivative 로 이동하면서 개선 가능(왜냐하면 convex)<br/>

### 1. 모델 구현

In [1]:
import tensorflow as tf

In [2]:
#1.데이터 및 변수 설정
x_data = [[1,2,1,1],
          [2,1,3,2],
          [3,1,3,4],
          [4,1,5,5],
          [1,7,5,5],
          [1,2,5,6],
          [1,6,6,6],
          [1,7,7,7]]

y_data = [[0,0,1],
          [0,0,1],
          [0,0,1],
          [0,1,0],
          [0,1,0],
          [0,1,0],
          [1,0,0],
          [1,0,0]]

X = tf.placeholder("float", [None, 4])
Y = tf.placeholder("float", [None, 3])
nb_classes = 3

W = tf.Variable(tf.random_normal([4, nb_classes]), name="weight")
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

In [3]:
#2. 가설 설정
#tf.nn.softmax computes softmax activation
#softmax = exp(Logits) / reduce_sum(exp(Logits), dim)
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

In [4]:
#3. cost 함수
#Cross Entropy Loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis),))

In [5]:
#4. train
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [6]:
#5. Launch
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(2001):
        sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
        
        if step % 200 == 0:
            print(step, sess.run(cost, feed_dict={X:x_data, Y:y_data}))
    
    #6. Testing & One-hot encoding
    a = sess.run(hypothesis, feed_dict={X:[[1,11,7,9]]})
    print(a, sess.run(tf.argmax(a, 1)))
    
    all = sess.run(hypothesis, feed_dict={X: [[1,11,7,9],
                                              [1,3,4,3],
                                              [1,1,0,1]]})
    print(all)

0 126.9
200 49.4237
400 18.1062
600 2.0185
800 55.5735
1000 0.0242367
1200 0.0161528
1400 0.0129173
1600 0.0112206
1800 0.0102909
2000 0.00979997
[[  9.21498121e-12   1.00000000e+00   8.31275221e-14]] [1]
[[  9.21498121e-12   1.00000000e+00   8.31275153e-14]
 [  9.99859095e-01   1.40729462e-04   7.95577648e-08]
 [  1.32816656e-35   1.38087417e-13   1.00000000e+00]]


### 2. Fancy Softmax Classifer

In [7]:
#기존
hypothesis = tf.nn.softmax(tf.matmul(X,W) + b)
cost = tf.reduce_mean(-tf.reduce_mean(Y * tf.log(hypothesis), axis=1))

#현재
logits = tf.matmul(X,W)+b
cost_i = tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=Y_one_hot)
cost = tf.reduce_mean(cost_i)

NameError: name 'Y_one_hot' is not defined

In [90]:
import numpy as np

In [91]:
#1. 데이터 및 변수 설정
xy = np.loadtxt('./data/data-04-zoo.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

nb_classes = 7

X = tf.placeholder(tf.float32, [None, 16])
Y = tf.placeholder(tf.int32, [None, 1])

#Y_one_hot 출력
Y_one_hot = tf.one_hot(Y, nb_classes)
Y_one_hot_shape = tf.shape(Y_one_hot)

sess = tf.Session()
sess.run([Y_one_hot, Y_one_hot_shape], feed_dict={Y: y_data})

[array([[[ 1.,  0.,  0.,  0.,  0.,  0.,  0.]],
 
        [[ 1.,  0.,  0.,  0.,  0.,  0.,  0.]],
 
        [[ 0.,  0.,  0.,  1.,  0.,  0.,  0.]],
 
        [[ 1.,  0.,  0.,  0.,  0.,  0.,  0.]],
 
        [[ 1.,  0.,  0.,  0.,  0.,  0.,  0.]],
 
        [[ 1.,  0.,  0.,  0.,  0.,  0.,  0.]],
 
        [[ 1.,  0.,  0.,  0.,  0.,  0.,  0.]],
 
        [[ 0.,  0.,  0.,  1.,  0.,  0.,  0.]],
 
        [[ 0.,  0.,  0.,  1.,  0.,  0.,  0.]],
 
        [[ 1.,  0.,  0.,  0.,  0.,  0.,  0.]],
 
        [[ 1.,  0.,  0.,  0.,  0.,  0.,  0.]],
 
        [[ 0.,  1.,  0.,  0.,  0.,  0.,  0.]],
 
        [[ 0.,  0.,  0.,  1.,  0.,  0.,  0.]],
 
        [[ 0.,  0.,  0.,  0.,  0.,  0.,  1.]],
 
        [[ 0.,  0.,  0.,  0.,  0.,  0.,  1.]],
 
        [[ 0.,  0.,  0.,  0.,  0.,  0.,  1.]],
 
        [[ 0.,  1.,  0.,  0.,  0.,  0.,  0.]],
 
        [[ 1.,  0.,  0.,  0.,  0.,  0.,  0.]],
 
        [[ 0.,  0.,  0.,  1.,  0.,  0.,  0.]],
 
        [[ 1.,  0.,  0.,  0.,  0.,  0.,  0.]],
 
        [[ 0.,  1., 

In [92]:
#Y_one_hot shape 조정
Y_one_hot = tf.one_hot(Y, nb_classes)
Y_one_hot = tf.reshape(Y_one_hot, [-1, nb_classes])
Y_one_hot_check = tf.argmax(Y_one_hot, 1)

sess = tf.Session()
sess.run([Y_one_hot, Y_one_hot_check], feed_dict={Y: y_data})

[array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 1.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  1.,  0.,  0.,  0.],
        [ 1.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 1.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 1.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 1.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  1.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  1.,  0.,  0.,  0.],
        [ 1.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 1.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  1.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  1.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  1.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  1.],
        [ 0.,  1.,  0.,  0.,  0.,  0.,  0.],
        [ 1.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  1.,  0.,  0.,  0.],
        [ 1.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.,  0.,  0.,  0.],
        [ 

In [93]:
#Y_one_hot shape 조정
Y_one_hot = tf.one_hot(Y, nb_classes)
Y_one_hot = tf.reshape(Y_one_hot, [-1, nb_classes])
Y_one_hot_check = tf.argmax(Y_one_hot, 1)

In [94]:
W = tf.Variable(tf.random_normal([16, nb_classes]), name="weight")
b = tf.Variable(tf.random_normal([nb_classes]), name="bias")

In [95]:
#2. hypothesis
#tf.nn.softmax computes softmax activations
logits = tf.matmul(X,W) + b
hypothesis = tf.nn.softmax(logits)

#3. cost
#cross entropy cost/loss
cost_i = tf.nn.softmax_cross_entropy_with_logits(logits=logits,
                                                 labels=Y_one_hot)
cost = tf.reduce_mean(cost_i)

In [96]:
#4. train
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [97]:
# prediction 
prediction = tf.argmax(hypothesis, 1)
correct_prediction = tf.equal(prediction, tf.argmax(Y_one_hot, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

In [98]:
#출력
prediction = tf.argmax(hypothesis, 1)
arg_max = tf.argmax(Y_one_hot, 1)

sess= tf.Session()
sess.run(tf.global_variables_initializer())
print(sess.run(prediction, feed_dict={X: x_data, Y: y_data}))
print(sess.run(correct_prediction, feed_dict={X: x_data, Y: y_data}))


[6 6 1 6 6 6 6 1 1 6 6 6 1 4 4 6 6 6 4 6 6 6 6 6 6 6 6 6 6 5 6 6 5 6 1 6 6
 6 1 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 4 6 4 1 1 4 6 6 6 6 6 6 6 6 6 1
 5 6 4 4 6 6 1 1 1 6 6 6 4 6 6 6 6 6 4 6 6 6 6 6 6 1 6]
[False False False False False False False False False False False False
 False False False  True False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False  True False
 False False False False False  True False False False False False False
 False False False False False False False False False False False False
  True False False False False False False False False False False False
 False  True False False False False False False False False False False
 False False False False False]


In [99]:
#5. Launch
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(2000):
        sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
    
        if step % 200 == 0:
            loss, acc = sess.run([cost, accuracy], feed_dict={X: x_data, Y: y_data})

            print("Step: {:5}\tLoss: {:.3f}\tAcc: {:.2%}".format(step, loss, acc))

        pred = sess.run(prediction, feed_dict={X: x_data})
    
    for p, y in zip(pred, y_data.flatten()):
        print("[{}] Prediction: {} True Y: {}".format(p==int(y), p, int(y)))

Step:     0	Loss: 4.224	Acc: 16.83%
Step:   200	Loss: 0.348	Acc: 92.08%
Step:   400	Loss: 0.208	Acc: 94.06%
Step:   600	Loss: 0.149	Acc: 97.03%
Step:   800	Loss: 0.117	Acc: 99.01%
Step:  1000	Loss: 0.096	Acc: 99.01%
Step:  1200	Loss: 0.082	Acc: 100.00%
Step:  1400	Loss: 0.071	Acc: 100.00%
Step:  1600	Loss: 0.063	Acc: 100.00%
Step:  1800	Loss: 0.057	Acc: 100.00%
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 3 True Y: 3
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 3 True Y: 3
[True] Prediction: 3 True Y: 3
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 1 True Y: 1
[True] Prediction: 3 True Y: 3
[True] Prediction: 6 True Y: 6
[True] Prediction: 6 True Y: 6
[True] Prediction: 6 True Y: 6
[True] Prediction: 1 True Y: 1
[True] Prediction: 0 True Y: 0
[True] Prediction: 3 True Y: 3
[True] Prediction: 0 True Y: 0
[True] Predictio

In [100]:
print(y_data)
print(y_data.flatten())

[[ 0.]
 [ 0.]
 [ 3.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 3.]
 [ 3.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 3.]
 [ 6.]
 [ 6.]
 [ 6.]
 [ 1.]
 [ 0.]
 [ 3.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 5.]
 [ 4.]
 [ 4.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 5.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 3.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 3.]
 [ 5.]
 [ 5.]
 [ 1.]
 [ 5.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 6.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 5.]
 [ 4.]
 [ 6.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 3.]
 [ 3.]
 [ 2.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 6.]
 [ 3.]
 [ 0.]
 [ 0.]
 [ 2.]
 [ 6.]
 [ 1.]
 [ 1.]
 [ 2.]
 [ 6.]
 [ 3.]
 [ 1.]
 [ 0.]
 [ 6.]
 [ 3.]
 [ 1.]
 [ 5.]
 [ 4.]
 [ 2.]
 [ 2.]
 [ 3.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 5.]
 [ 0.]
 [ 6.]
 [ 1.]]
[ 0.  0.  3.  0.  0.  0.  0.  3.  3.  0.  0.  1.  3.  6.  6.  6.  1.  0.
  3.  0.  1.  1.  0.  1.  5.  4.  4.  0.  0.  0.  5.  0.  0.  1.  3.  0.
  0.  1.  3.  5.  5.  1.  5.  1.  0.  0.  6.  0.  0.  0.  0.  5.  4.  6.
  0.  0.  1.  1.  1.  1.  3.  3.  2.  0.  0.  0.  0.  0.  0.  0.  0.  1.


### 3. 복습

In [2]:
import numpy as np
import tensorflow as tf

#### 1. 데이터 정리

In [101]:
xy = np.loadtxt('./data/data-04-zoo.csv', delimiter=',', dtype=np.float32)

In [102]:
x_data = xy[:,:-1]
y_data = xy[:,-1]

In [103]:
#클래스는 7가지 -> one_hot encoding으로 변경
y_data = y_data.astype(int)

In [104]:
y_one_hot = np.zeros((len(y_data), np.max(y_data) + 1))
y_one_hot[np.arange(len(y_data)), y_data] = 1

내가 정의해야 하는 입력 데이터는 x_data 와 y_data에 대한 Placeholder<br/>
내가 정의해야 하는 변수는 Softmax Regression의 Weight와 Bias

In [105]:
X = tf.placeholder(dtype=tf.float32, shape=[None, 16])
Y = tf.placeholder(dtype=tf.float32, shape=[None, 7])

In [106]:
W = tf.Variable(tf.random_normal([16, 7]), dtype=tf.float32)
b = tf.Variable(tf.zeros([7]), dtype=tf.float32)

#### 2. cost function 정의

In [107]:
# Softmax
pred = tf.nn.softmax(tf.matmul(X, W) + b)

In [108]:
# Minimize error using cross entropy
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(pred), reduction_indices=1))

#### 3. gradient descent 정의

In [109]:
# Gradient Descent
optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)

#### 4. 변수 초기화

In [110]:
# Initialize the variables (i.e. assign their default value)
init = tf.global_variables_initializer()

#### 4-1. 예측

In [111]:
# prediction 
prediction = tf.argmax(pred, 1)
correct_prediction = tf.equal(prediction, tf.argmax(y_one_hot, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

#### 5. 학습

In [117]:
with tf.Session() as sess:
    
    # 초기화
    sess.run(init)
    
    for step in range(2000):
        [icost, iaccuracy, ioptimizer] = sess.run([cost, accuracy, optimizer], feed_dict= {X: x_data, Y: y_one_hot})
        
        if step % 200 == 0:
            print(step, iaccuracy, icost)
            
        pred = sess.run(prediction, feed_dict={X: x_data})
    
    for p, y in zip(pred, y_data.flatten()):
        print("[{}] Prediction: {} True Y: {}".format(p==int(y), p, int(y)))

0 0.158416 3.30159
200 1.0 0.0516882
400 1.0 0.0268815
600 1.0 0.0183329
800 1.0 0.0139747
1000 1.0 0.0113195
1200 1.0 0.00952683
1400 1.0 0.00823258
1600 1.0 0.00725301
1800 1.0 0.00648504
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 3 True Y: 3
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 3 True Y: 3
[True] Prediction: 3 True Y: 3
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 1 True Y: 1
[True] Prediction: 3 True Y: 3
[True] Prediction: 6 True Y: 6
[True] Prediction: 6 True Y: 6
[True] Prediction: 6 True Y: 6
[True] Prediction: 1 True Y: 1
[True] Prediction: 0 True Y: 0
[True] Prediction: 3 True Y: 3
[True] Prediction: 0 True Y: 0
[True] Prediction: 1 True Y: 1
[True] Prediction: 1 True Y: 1
[True] Prediction: 0 True Y: 0
[True] Prediction: 1 True Y: 1
[True] Prediction: 5 True Y: 5
[True] Prediction: 4 True Y: 4
[Tru

In [116]:
learning_rate = 0.01