# Softmax Regression

<img src="./photo/softmax1.png">

### 0. 개념 다지기

1. softmax는 logistic regression의 multiclass 판<br/>
    -> binary classification에서 multiclass classification으로 변경<br/><br/>
    
2. logistic regression의 경우 g(z): sigmoid function으로 H(X)를 0 <= H(X) = g(z) = g(X*w) <=1로 유지하고, 출력을 확률 값으로 변경<br/>
    -> sigmoid regression의 경우 H(X): softmax function(e^Wk.T*x / sigma(e^Wi.T.x))를 사용<br/>
    -> 마찬가지로 각 Class 에 속할 확률으로 표현<br/><br/>

3. costfunction
    -> cross entropy 개념<br/>
    -> D(S, L) = sigma(실제 값(Li) * log(예측값=softmax(i))<br/>
    -> W = W - learning_rate * derivative 로 이동하면서 개선 가능(왜냐하면 convex)<br/>

### 1. 모델 구현

In [1]:
import tensorflow as tf

In [2]:
#1.데이터 및 변수 설정
x_data = [[1,2,1,1],
          [2,1,3,2],
          [3,1,3,4],
          [4,1,5,5],
          [1,7,5,5],
          [1,2,5,6],
          [1,6,6,6],
          [1,7,7,7]]

y_data = [[0,0,1],
          [0,0,1],
          [0,0,1],
          [0,1,0],
          [0,1,0],
          [0,1,0],
          [1,0,0],
          [1,0,0]]

X = tf.placeholder("float", [None, 4])
Y = tf.placeholder("float", [None, 3])
nb_classes = 3

W = tf.Variable(tf.random_normal([4, nb_classes]), name="weight")
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

In [3]:
#2. 가설 설정
#tf.nn.softmax computes softmax activation
#softmax = exp(Logits) / reduce_sum(exp(Logits), dim)
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

In [4]:
#3. cost 함수
#Cross Entropy Loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis),))

In [5]:
#4. train
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [6]:
#5. Launch
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(2001):
        sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
        
        if step % 200 == 0:
            print(step, sess.run(cost, feed_dict={X:x_data, Y:y_data}))
    
    #6. Testing & One-hot encoding
    a = sess.run(hypothesis, feed_dict={X:[[1,11,7,9]]})
    print(a, sess.run(tf.argmax(a, 1)))
    
    all = sess.run(hypothesis, feed_dict={X: [[1,11,7,9],
                                              [1,3,4,3],
                                              [1,1,0,1]]})
    print(all)

0 126.9
200 49.4237
400 18.1062
600 2.0185
800 55.5735
1000 0.0242367
1200 0.0161528
1400 0.0129173
1600 0.0112206
1800 0.0102909
2000 0.00979997
[[  9.21498121e-12   1.00000000e+00   8.31275221e-14]] [1]
[[  9.21498121e-12   1.00000000e+00   8.31275153e-14]
 [  9.99859095e-01   1.40729462e-04   7.95577648e-08]
 [  1.32816656e-35   1.38087417e-13   1.00000000e+00]]


### 2. Fancy Softmax Classifer

In [7]:
#기존
hypothesis = tf.nn.softmax(tf.matmul(X,W) + b)
cost = tf.reduce_mean(-tf.reduce_mean(Y * tf.log(hypothesis), axis=1))

#현재
logits = tf.matmul(X,W)+b
cost_i = tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=Y_one_hot)
cost = tf.reduce_mean(cost_i)

NameError: name 'Y_one_hot' is not defined

In [8]:
import numpy as np

In [10]:
#1. 데이터 및 변수 설정
xy = np.loadtxt('./data/data-04-zoo.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

nb_classes = 7

X = tf.placeholder(tf.float32, [None, 16])
Y = tf.placeholder(tf.int32, [None, 1])

#Y_one_hot 출력
Y_one_hot = tf.one_hot(Y, nb_classes)
Y_one_hot_shape = tf.shape(Y_one_hot)

sess = tf.Session()
sess.run([Y_one_hot, Y_one_hot_shape], feed_dict={Y: y_data})

[array([[[ 1.,  0.,  0.,  0.,  0.,  0.,  0.]],
 
        [[ 1.,  0.,  0.,  0.,  0.,  0.,  0.]],
 
        [[ 0.,  0.,  0.,  1.,  0.,  0.,  0.]],
 
        [[ 1.,  0.,  0.,  0.,  0.,  0.,  0.]],
 
        [[ 1.,  0.,  0.,  0.,  0.,  0.,  0.]],
 
        [[ 1.,  0.,  0.,  0.,  0.,  0.,  0.]],
 
        [[ 1.,  0.,  0.,  0.,  0.,  0.,  0.]],
 
        [[ 0.,  0.,  0.,  1.,  0.,  0.,  0.]],
 
        [[ 0.,  0.,  0.,  1.,  0.,  0.,  0.]],
 
        [[ 1.,  0.,  0.,  0.,  0.,  0.,  0.]],
 
        [[ 1.,  0.,  0.,  0.,  0.,  0.,  0.]],
 
        [[ 0.,  1.,  0.,  0.,  0.,  0.,  0.]],
 
        [[ 0.,  0.,  0.,  1.,  0.,  0.,  0.]],
 
        [[ 0.,  0.,  0.,  0.,  0.,  0.,  1.]],
 
        [[ 0.,  0.,  0.,  0.,  0.,  0.,  1.]],
 
        [[ 0.,  0.,  0.,  0.,  0.,  0.,  1.]],
 
        [[ 0.,  1.,  0.,  0.,  0.,  0.,  0.]],
 
        [[ 1.,  0.,  0.,  0.,  0.,  0.,  0.]],
 
        [[ 0.,  0.,  0.,  1.,  0.,  0.,  0.]],
 
        [[ 1.,  0.,  0.,  0.,  0.,  0.,  0.]],
 
        [[ 0.,  1., 

In [11]:
#Y_one_hot shape 조정
Y_one_hot = tf.one_hot(Y, nb_classes)
Y_one_hot = tf.reshape(Y_one_hot, [-1, nb_classes])
Y_one_hot_check = tf.argmax(Y_one_hot, 1)

sess = tf.Session()
sess.run([Y_one_hot, Y_one_hot_check], feed_dict={Y: y_data})

[array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 1.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  1.,  0.,  0.,  0.],
        [ 1.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 1.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 1.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 1.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  1.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  1.,  0.,  0.,  0.],
        [ 1.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 1.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  1.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  1.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  1.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  1.],
        [ 0.,  1.,  0.,  0.,  0.,  0.,  0.],
        [ 1.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  1.,  0.,  0.,  0.],
        [ 1.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.,  0.,  0.,  0.],
        [ 

In [12]:
#Y_one_hot shape 조정
Y_one_hot = tf.one_hot(Y, nb_classes)
Y_one_hot = tf.reshape(Y_one_hot, [-1, nb_classes])
Y_one_hot_check = tf.argmax(Y_one_hot, 1)

In [13]:
W = tf.Variable(tf.random_normal([16, nb_classes]), name="weight")
b = tf.Variable(tf.random_normal([nb_classes]), name="bias")

In [14]:
#2. hypothesis
#tf.nn.softmax computes softmax activations
logits = tf.matmul(X,W) + b
hypothesis = tf.nn.softmax(logits)

#3. cost
#cross entropy cost/loss
cost_i = tf.nn.softmax_cross_entropy_with_logits(logits=logits,
                                                 labels=Y_one_hot)
cost = tf.reduce_mean(cost_i)

In [15]:
#4. train
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [16]:
# prediction 
prediction = tf.argmax(hypothesis, 1)
correct_prediction = tf.equal(prediction, tf.argmax(Y_one_hot, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

In [17]:
#출력
prediction = tf.argmax(hypothesis, 1)
arg_max = tf.argmax(Y_one_hot, 1)

sess= tf.Session()
sess.run(tf.global_variables_initializer())
print(sess.run(prediction, feed_dict={X: x_data, Y: y_data}))
print(sess.run(correct_prediction, feed_dict={X: x_data, Y: y_data}))


[2 2 6 2 2 2 2 1 6 2 2 2 6 2 2 2 2 2 6 6 2 3 2 3 2 2 2 2 2 2 2 2 2 2 6 2 2
 2 6 2 2 2 2 3 2 2 2 2 2 2 2 2 2 2 2 2 3 2 3 3 6 6 1 2 2 2 6 2 2 2 2 3 2 6
 6 6 1 2 2 2 2 2 6 3 2 2 1 3 2 2 3 2 6 2 2 1 1 2 2 2 3]
[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False  True False False False
 False False False False False False False  True False False False  True
 False False False False False]


In [18]:
#5. Launch
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(2000):
        sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
    
        if step % 200 == 0:
            loss, acc = sess.run([cost, accuracy], feed_dict={X: x_data, Y: y_data})

            print("Step: {:5}\tLoss: {:.3f}\tAcc: {:.2%}".format(step, loss, acc))

        pred = sess.run(prediction, feed_dict={X: x_data})
    
    for p, y in zip(pred, y_data.flatten()):
        print("[{}] Prediction: {} True Y: {}".format(p==int(y), p, int(y)))

Step:     0	Loss: 4.395	Acc: 19.80%
Step:   200	Loss: 0.401	Acc: 88.12%
Step:   400	Loss: 0.230	Acc: 95.05%
Step:   600	Loss: 0.162	Acc: 97.03%
Step:   800	Loss: 0.126	Acc: 97.03%
Step:  1000	Loss: 0.103	Acc: 99.01%
Step:  1200	Loss: 0.088	Acc: 100.00%
Step:  1400	Loss: 0.076	Acc: 100.00%
Step:  1600	Loss: 0.067	Acc: 100.00%
Step:  1800	Loss: 0.060	Acc: 100.00%
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 3 True Y: 3
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 3 True Y: 3
[True] Prediction: 3 True Y: 3
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 1 True Y: 1
[True] Prediction: 3 True Y: 3
[True] Prediction: 6 True Y: 6
[True] Prediction: 6 True Y: 6
[True] Prediction: 6 True Y: 6
[True] Prediction: 1 True Y: 1
[True] Prediction: 0 True Y: 0
[True] Prediction: 3 True Y: 3
[True] Prediction: 0 True Y: 0
[True] Predictio

In [19]:
print(y_data)
print(y_data.flatten())

[[ 0.]
 [ 0.]
 [ 3.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 3.]
 [ 3.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 3.]
 [ 6.]
 [ 6.]
 [ 6.]
 [ 1.]
 [ 0.]
 [ 3.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 5.]
 [ 4.]
 [ 4.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 5.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 3.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 3.]
 [ 5.]
 [ 5.]
 [ 1.]
 [ 5.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 6.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 5.]
 [ 4.]
 [ 6.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 3.]
 [ 3.]
 [ 2.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 6.]
 [ 3.]
 [ 0.]
 [ 0.]
 [ 2.]
 [ 6.]
 [ 1.]
 [ 1.]
 [ 2.]
 [ 6.]
 [ 3.]
 [ 1.]
 [ 0.]
 [ 6.]
 [ 3.]
 [ 1.]
 [ 5.]
 [ 4.]
 [ 2.]
 [ 2.]
 [ 3.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 5.]
 [ 0.]
 [ 6.]
 [ 1.]]
[ 0.  0.  3.  0.  0.  0.  0.  3.  3.  0.  0.  1.  3.  6.  6.  6.  1.  0.
  3.  0.  1.  1.  0.  1.  5.  4.  4.  0.  0.  0.  5.  0.  0.  1.  3.  0.
  0.  1.  3.  5.  5.  1.  5.  1.  0.  0.  6.  0.  0.  0.  0.  5.  4.  6.
  0.  0.  1.  1.  1.  1.  3.  3.  2.  0.  0.  0.  0.  0.  0.  0.  0.  1.
